application: teammacdown
version: beta-1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: style
  
- url: /img
  static_dir: img

- url: /js
  static_dir: js
  
- url: /static
  static_dir: static
  
- url: /.*
  script: teammacdown.py